[workspace]
resolver = "3"
members = ["alpaca", "amber_lume", "builder", "lume/core", "lume/desktop", "lume/android"]
default-members = ["alpaca", "amber_lume", "builder", "lume/core", "lume/desktop"]

[workspace.dependencies]
rkyv = { version = "0.8.15", features = ["bytecheck"] }
bytemuck = { version = "1.25.0", features = ["derive"] }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.22" }

[profile.dev]
opt-level = 0
debug = 2
incremental = true
overflow-checks = true
debug-assertions = true

[profile.release]
incremental = false
debug = 0
strip = true
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3

[profile.profiling]
inherits = "release"
debug = true
lto = false
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3
