[package]
name = "AmberLume"
version = "0.0.1"
edition = "2024"
build = "build.rs"

[dependencies]
winit = "0.30.12"
tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
anyhow = "1.0.100"
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
memmap2 = "0.9.8"
dashmap = "7.0.0-rc2"
arc-swap = "1.7.1"
parking_lot = "0.12.5"
blake3 = "1.8.2"
walkdir = "2.5.0"
bytemuck = "1.24.0"

[build-dependencies]
glob = "0.3.3"
shaderc = "0.10.1"
anyhow = "1.0.100"

[profile.dev]
opt-level = 0
debug = 2
incremental = true
overflow-checks = true
debug-assertions = true

[profile.release]
incremental = false
debug = 0
strip = true
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3

[profile.profiling]
inherits = "release"
debug = true
lto = false
codegen-units = 1
