[package]
name = "android"
version = "0.3.0"
edition = "2024"

[dependencies]
ui = { path = "../../ui" }
amber_lume = { path = "../../amber_lume" }
settings = { path = "../../settings" }
statistics = { path = "../../statistics" }
core = { path = "../core" }
gpu = { path = "../../gpu" }
input = { path = "../../input" }
resource_reader = { path = "../../resource_reader" }
raw-window-handle = { workspace = true }
parking_lot = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
[target.'cfg(target_os = "android")'.dependencies]
android-activity = { workspace = true }
tracing-android = { workspace = true }
yakui = { workspace = true }
ndk = { workspace = true }

[lib]
name = "lume_android"
path = "src/lib.rs"
crate-type = ["cdylib"]
