#version 460

#include "common.glsl"

layout(local_size_x = 256) in;

layout(push_constant) uniform PushConstants {
    uint64_t scene_buffer_device_address;

    uint entity_count;
} push_constants;

void main() {
    SceneGpuData scene = SceneBuffer(push_constants.scene_buffer_device_address).data;

    uint entity_id = gl_GlobalInvocationID.x;
    if (entity_id >= push_constants.entity_count) return;

    IndirectBuffer indirect = IndirectBuffer(scene.indirect_buffer_device_address);
    DrawCountBuffer draw_count = DrawCountBuffer(scene.draw_count_buffer_device_address);
    EntityBuffer entities = EntityBuffer(scene.entity_buffer_device_address);
    ModelBuffer models = ModelBuffer(scene.model_buffer_device_address);
    PrimitiveBuffer primitives = PrimitiveBuffer(scene.primitive_buffer_device_address);
    DrawBufferWrite draws = DrawBufferWrite(scene.draw_buffer_device_address);

    EntityGpuData entity = entities.data[entity_id];

    if (!is_resource_available(scene.model_availability_buffer_device_address, entity.model_index)) return;
    ModelGpuData model = models.data[entity.model_index];

    uint command_index = atomicAdd(draw_count.count, model.primitive_count);

    for (uint i = 0; i < model.primitive_count; i++) {
        PrimitiveGpuData primitive = primitives.data[model.primitive_offset + i];

        uint current_command = command_index + i;
        uint command_offset = current_command * 5;

        indirect.commands[command_offset + 0] = primitive.index_count;
        indirect.commands[command_offset + 1] = 1;
        indirect.commands[command_offset + 2] = primitive.index_offset;
        indirect.commands[command_offset + 3] = primitive.vertex_offset;
        indirect.commands[command_offset + 4] = entity_id;

        draws.data[current_command].entity_index = entity_id;
        draws.data[current_command].primitive_index = model.primitive_offset + i;
    }
}
