[package]
name = "desktop"
version = "0.3.0"
edition = "2024"

[features]
default = []
x11 = []

[dependencies]
amber_lume = { path = "../../amber_lume" }
settings = { path = "../../settings" }
gpu = { path = "../../gpu" }
input = { path = "../../input" }
resource_reader = { path = "../../resource_reader" }
core = { path = "../core" }
winit = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }
walkdir = { workspace = true }
anyhow = { workspace = true }
memmap2 = { workspace = true }
parking_lot = { workspace = true }
