[package]
name = "amber_lume"
version = "0.0.1"
edition = "2024"

[dependencies]
rkyv = { version = "0.8.12", features = ["bytecheck"] }
tracing = { version = "0.1.41", features = ["attributes"] }
anyhow = "1.0.100"
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
raw-window-handle = "0.6.2"
dashmap = "7.0.0-rc2"
arc-swap = "1.7.1"
parking_lot = "0.12.5"
blake3 = "1.8.2"
bytemuck = { version = "1.24.0", features = ["derive"] }
gpu-allocator = { version = "0.28.0", features = ["vulkan"] }
glam = "0.30.9"
alpaca = { path = "../alpaca", features = ["unpacker"] }
shipyard = "0.10.0"
