[package]
name = "amber_lume"
version = "0.0.1"
edition = "2024"

[dependencies]
resource_data = { path = "../resource_data" }
rkyv = { workspace = true }
tracing = { version = "0.1.41", features = ["attributes"] }
anyhow = { workspace = true }
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
raw-window-handle = { workspace = true }
dashmap = "7.0.0-rc2"
parking_lot = { workspace = true }
ahash = "0.8.12"
bytemuck = { workspace = true }
gpu-allocator = { version = "0.28.0", features = ["vulkan"] }
rapier3d = { workspace = true }
glam = { workspace = true }
alpaca = { path = "../alpaca", features = ["unpacker"] }
shipyard = "0.11.0"
ktx2 = { version = "0.4.0" }
zstd = "0.13.3"
basis-universal = { version = "0.3.1" }
yakui = { workspace = true }
crossbeam-channel = "0.5.15"
arc-swap = "1.8.2"
