[package]
name = "amber_lume"
version = "0.0.1"
edition = "2024"

[dependencies]
builder = { path = "../builder", features = ["data"] }
rkyv = { workspace = true }
tracing = { version = "0.1.41", features = ["attributes"] }
anyhow = "1.0.100"
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
raw-window-handle = "0.6.2"
dashmap = "7.0.0-rc2"
parking_lot = "0.12.5"
blake3 = "1.8.2"
ahash = "0.8.12"
bytemuck = { workspace = true }
gpu-allocator = { version = "0.28.0", features = ["vulkan"] }
glam = "0.30.9"
alpaca = { path = "../alpaca", features = ["unpacker"] }
shipyard = "0.11.0"
ktx2 = { version = "0.4.0" }
zstd = "0.13.3"
basis-universal = { version = "0.3.1" }
rapier3d = { version = "0.31.0", features = ["simd-stable", "debug-render"] }
nalgebra = "0.34.1"
yakui = "0.3.0"
crossbeam-channel = "0.5.15"
arc-swap = "1.8.2"
