[package]
name = "builder"
version = "0.5.0"
edition = "2024"

[dependencies]
amber_lume = { path = "../amber_lume" }
alpaca = { path = "../alpaca", features = ["packer"] }
anyhow = { workspace = true }
walkdir = "2.5.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
blake3 = "1.5"
tracing = { workspace = true, features = ["attributes"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
rayon = "1.11.0"
shaderc = { version = "0.10.1" }
memmap2 = { workspace = true }
gltf = { version = "1.4.1", features = ["extras"] }
rkyv = { workspace = true }
dashmap = "7.0.0-rc2"
bytemuck = { workspace = true }
glam = "0.32.1"
