[package]
name = "builder"
version = "0.5.0"
edition = "2024"

[dependencies]
resource_data = { path = "../resource_data" }
alpaca = { path = "../alpaca", features = ["packer"] }
anyhow = { workspace = true }
walkdir = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
blake3 = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
rayon = { workspace = true }
shaderc = { workspace = true }
memmap2 = { workspace = true }
gltf = { workspace = true }
rkyv = { workspace = true }
dashmap = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
parking_lot = { workspace = true }
