// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use core::cmp::Ordering;
use core::mem;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod alpaca {

    use core::cmp::Ordering;
    use core::mem;

    extern crate flatbuffers;
    use self::flatbuffers::{EndianScalar, Follow};

    // struct AABB, aligned to 4
    #[repr(transparent)]
    #[derive(Clone, Copy, PartialEq)]
    pub struct AABB(pub [u8; 24]);
    impl Default for AABB {
        fn default() -> Self {
            Self([0; 24])
        }
    }
    impl core::fmt::Debug for AABB {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("AABB")
                .field("min_x", &self.min_x())
                .field("min_y", &self.min_y())
                .field("min_z", &self.min_z())
                .field("max_x", &self.max_x())
                .field("max_y", &self.max_y())
                .field("max_z", &self.max_z())
                .finish()
        }
    }

    impl flatbuffers::SimpleToVerifyInSlice for AABB {}
    impl<'a> flatbuffers::Follow<'a> for AABB {
        type Inner = &'a AABB;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            unsafe { <&'a AABB>::follow(buf, loc) }
        }
    }
    impl<'a> flatbuffers::Follow<'a> for &'a AABB {
        type Inner = &'a AABB;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            unsafe { flatbuffers::follow_cast_ref::<AABB>(buf, loc) }
        }
    }
    impl<'b> flatbuffers::Push for AABB {
        type Output = AABB;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            let src = unsafe {
                ::core::slice::from_raw_parts(
                    self as *const AABB as *const u8,
                    <Self as flatbuffers::Push>::size(),
                )
            };
            dst.copy_from_slice(src);
        }
        #[inline]
        fn alignment() -> flatbuffers::PushAlignment {
            flatbuffers::PushAlignment::new(4)
        }
    }

    impl<'a> flatbuffers::Verifiable for AABB {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.in_buffer::<Self>(pos)
        }
    }

    impl<'a> AABB {
        #[allow(clippy::too_many_arguments)]
        pub fn new(min_x: f32, min_y: f32, min_z: f32, max_x: f32, max_y: f32, max_z: f32) -> Self {
            let mut s = Self([0; 24]);
            s.set_min_x(min_x);
            s.set_min_y(min_y);
            s.set_min_z(min_z);
            s.set_max_x(max_x);
            s.set_max_y(max_y);
            s.set_max_z(max_z);
            s
        }

        pub fn min_x(&self) -> f32 {
            let mut mem = core::mem::MaybeUninit::<<f32 as EndianScalar>::Scalar>::uninit();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            EndianScalar::from_little_endian(unsafe {
                core::ptr::copy_nonoverlapping(
                    self.0[0..].as_ptr(),
                    mem.as_mut_ptr() as *mut u8,
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
                mem.assume_init()
            })
        }

        pub fn set_min_x(&mut self, x: f32) {
            let x_le = x.to_little_endian();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            unsafe {
                core::ptr::copy_nonoverlapping(
                    &x_le as *const _ as *const u8,
                    self.0[0..].as_mut_ptr(),
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
            }
        }

        pub fn min_y(&self) -> f32 {
            let mut mem = core::mem::MaybeUninit::<<f32 as EndianScalar>::Scalar>::uninit();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            EndianScalar::from_little_endian(unsafe {
                core::ptr::copy_nonoverlapping(
                    self.0[4..].as_ptr(),
                    mem.as_mut_ptr() as *mut u8,
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
                mem.assume_init()
            })
        }

        pub fn set_min_y(&mut self, x: f32) {
            let x_le = x.to_little_endian();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            unsafe {
                core::ptr::copy_nonoverlapping(
                    &x_le as *const _ as *const u8,
                    self.0[4..].as_mut_ptr(),
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
            }
        }

        pub fn min_z(&self) -> f32 {
            let mut mem = core::mem::MaybeUninit::<<f32 as EndianScalar>::Scalar>::uninit();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            EndianScalar::from_little_endian(unsafe {
                core::ptr::copy_nonoverlapping(
                    self.0[8..].as_ptr(),
                    mem.as_mut_ptr() as *mut u8,
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
                mem.assume_init()
            })
        }

        pub fn set_min_z(&mut self, x: f32) {
            let x_le = x.to_little_endian();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            unsafe {
                core::ptr::copy_nonoverlapping(
                    &x_le as *const _ as *const u8,
                    self.0[8..].as_mut_ptr(),
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
            }
        }

        pub fn max_x(&self) -> f32 {
            let mut mem = core::mem::MaybeUninit::<<f32 as EndianScalar>::Scalar>::uninit();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            EndianScalar::from_little_endian(unsafe {
                core::ptr::copy_nonoverlapping(
                    self.0[12..].as_ptr(),
                    mem.as_mut_ptr() as *mut u8,
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
                mem.assume_init()
            })
        }

        pub fn set_max_x(&mut self, x: f32) {
            let x_le = x.to_little_endian();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            unsafe {
                core::ptr::copy_nonoverlapping(
                    &x_le as *const _ as *const u8,
                    self.0[12..].as_mut_ptr(),
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
            }
        }

        pub fn max_y(&self) -> f32 {
            let mut mem = core::mem::MaybeUninit::<<f32 as EndianScalar>::Scalar>::uninit();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            EndianScalar::from_little_endian(unsafe {
                core::ptr::copy_nonoverlapping(
                    self.0[16..].as_ptr(),
                    mem.as_mut_ptr() as *mut u8,
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
                mem.assume_init()
            })
        }

        pub fn set_max_y(&mut self, x: f32) {
            let x_le = x.to_little_endian();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            unsafe {
                core::ptr::copy_nonoverlapping(
                    &x_le as *const _ as *const u8,
                    self.0[16..].as_mut_ptr(),
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
            }
        }

        pub fn max_z(&self) -> f32 {
            let mut mem = core::mem::MaybeUninit::<<f32 as EndianScalar>::Scalar>::uninit();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            EndianScalar::from_little_endian(unsafe {
                core::ptr::copy_nonoverlapping(
                    self.0[20..].as_ptr(),
                    mem.as_mut_ptr() as *mut u8,
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
                mem.assume_init()
            })
        }

        pub fn set_max_z(&mut self, x: f32) {
            let x_le = x.to_little_endian();
            // Safety:
            // Created from a valid Table for this object
            // Which contains a valid value in this slot
            unsafe {
                core::ptr::copy_nonoverlapping(
                    &x_le as *const _ as *const u8,
                    self.0[20..].as_mut_ptr(),
                    core::mem::size_of::<<f32 as EndianScalar>::Scalar>(),
                );
            }
        }
    }

    pub enum ModelOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct Model<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for Model<'a> {
        type Inner = Model<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> Model<'a> {
        pub const VT_MESHES: flatbuffers::VOffsetT = 4;
        pub const VT_BOUNDS: flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            Model { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args ModelArgs<'args>,
        ) -> flatbuffers::WIPOffset<Model<'bldr>> {
            let mut builder = ModelBuilder::new(_fbb);
            if let Some(x) = args.bounds {
                builder.add_bounds(x);
            }
            if let Some(x) = args.meshes {
                builder.add_meshes(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn meshes(
            &self,
        ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ModelMesh<'a>>>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<flatbuffers::ForwardsUOffset<
                    flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ModelMesh>>,
                >>(Model::VT_MESHES, None)
            }
        }
        #[inline]
        pub fn bounds(&self) -> Option<&'a AABB> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<AABB>(Model::VT_BOUNDS, None) }
        }
    }

    impl flatbuffers::Verifiable for Model<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<
                    flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ModelMesh>>,
                >>("meshes", Self::VT_MESHES, false)?
                .visit_field::<AABB>("bounds", Self::VT_BOUNDS, false)?
                .finish();
            Ok(())
        }
    }
    pub struct ModelArgs<'a> {
        pub meshes: Option<
            flatbuffers::WIPOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ModelMesh<'a>>>,
            >,
        >,
        pub bounds: Option<&'a AABB>,
    }
    impl<'a> Default for ModelArgs<'a> {
        #[inline]
        fn default() -> Self {
            ModelArgs {
                meshes: None,
                bounds: None,
            }
        }
    }

    pub struct ModelBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ModelBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_meshes(
            &mut self,
            meshes: flatbuffers::WIPOffset<
                flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<ModelMesh<'b>>>,
            >,
        ) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(Model::VT_MESHES, meshes);
        }
        #[inline]
        pub fn add_bounds(&mut self, bounds: &AABB) {
            self.fbb_
                .push_slot_always::<&AABB>(Model::VT_BOUNDS, bounds);
        }
        #[inline]
        pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ModelBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            ModelBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<Model<'a>> {
            let o = self.fbb_.end_table(self.start_);
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for Model<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("Model");
            ds.field("meshes", &self.meshes());
            ds.field("bounds", &self.bounds());
            ds.finish()
        }
    }
    pub enum ModelMeshOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct ModelMesh<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for ModelMesh<'a> {
        type Inner = ModelMesh<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> ModelMesh<'a> {
        pub const VT_NAME: flatbuffers::VOffsetT = 4;
        pub const VT_PRIMITIVES: flatbuffers::VOffsetT = 6;
        pub const VT_BOUNDS: flatbuffers::VOffsetT = 8;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            ModelMesh { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args ModelMeshArgs<'args>,
        ) -> flatbuffers::WIPOffset<ModelMesh<'bldr>> {
            let mut builder = ModelMeshBuilder::new(_fbb);
            if let Some(x) = args.bounds {
                builder.add_bounds(x);
            }
            if let Some(x) = args.primitives {
                builder.add_primitives(x);
            }
            if let Some(x) = args.name {
                builder.add_name(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn name(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(ModelMesh::VT_NAME, None)
            }
        }
        #[inline]
        pub fn primitives(
            &self,
        ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<MeshPrimitive<'a>>>>
        {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<flatbuffers::ForwardsUOffset<
                    flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<MeshPrimitive>>,
                >>(ModelMesh::VT_PRIMITIVES, None)
            }
        }
        #[inline]
        pub fn bounds(&self) -> Option<&'a AABB> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<AABB>(ModelMesh::VT_BOUNDS, None) }
        }
    }

    impl flatbuffers::Verifiable for ModelMesh<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
                .visit_field::<flatbuffers::ForwardsUOffset<
                    flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<MeshPrimitive>>,
                >>("primitives", Self::VT_PRIMITIVES, false)?
                .visit_field::<AABB>("bounds", Self::VT_BOUNDS, false)?
                .finish();
            Ok(())
        }
    }
    pub struct ModelMeshArgs<'a> {
        pub name: Option<flatbuffers::WIPOffset<&'a str>>,
        pub primitives: Option<
            flatbuffers::WIPOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<MeshPrimitive<'a>>>,
            >,
        >,
        pub bounds: Option<&'a AABB>,
    }
    impl<'a> Default for ModelMeshArgs<'a> {
        #[inline]
        fn default() -> Self {
            ModelMeshArgs {
                name: None,
                primitives: None,
                bounds: None,
            }
        }
    }

    pub struct ModelMeshBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ModelMeshBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(ModelMesh::VT_NAME, name);
        }
        #[inline]
        pub fn add_primitives(
            &mut self,
            primitives: flatbuffers::WIPOffset<
                flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<MeshPrimitive<'b>>>,
            >,
        ) {
            self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
                ModelMesh::VT_PRIMITIVES,
                primitives,
            );
        }
        #[inline]
        pub fn add_bounds(&mut self, bounds: &AABB) {
            self.fbb_
                .push_slot_always::<&AABB>(ModelMesh::VT_BOUNDS, bounds);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> ModelMeshBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            ModelMeshBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<ModelMesh<'a>> {
            let o = self.fbb_.end_table(self.start_);
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for ModelMesh<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("ModelMesh");
            ds.field("name", &self.name());
            ds.field("primitives", &self.primitives());
            ds.field("bounds", &self.bounds());
            ds.finish()
        }
    }
    pub enum MeshPrimitiveOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct MeshPrimitive<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for MeshPrimitive<'a> {
        type Inner = MeshPrimitive<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> MeshPrimitive<'a> {
        pub const VT_LOD0: flatbuffers::VOffsetT = 4;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            MeshPrimitive { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args MeshPrimitiveArgs<'args>,
        ) -> flatbuffers::WIPOffset<MeshPrimitive<'bldr>> {
            let mut builder = MeshPrimitiveBuilder::new(_fbb);
            if let Some(x) = args.lod0 {
                builder.add_lod0(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn lod0(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(MeshPrimitive::VT_LOD0, None)
            }
        }
    }

    impl flatbuffers::Verifiable for MeshPrimitive<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>("lod0", Self::VT_LOD0, false)?
                .finish();
            Ok(())
        }
    }
    pub struct MeshPrimitiveArgs<'a> {
        pub lod0: Option<flatbuffers::WIPOffset<&'a str>>,
    }
    impl<'a> Default for MeshPrimitiveArgs<'a> {
        #[inline]
        fn default() -> Self {
            MeshPrimitiveArgs { lod0: None }
        }
    }

    pub struct MeshPrimitiveBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> MeshPrimitiveBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_lod0(&mut self, lod0: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(MeshPrimitive::VT_LOD0, lod0);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> MeshPrimitiveBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            MeshPrimitiveBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<MeshPrimitive<'a>> {
            let o = self.fbb_.end_table(self.start_);
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for MeshPrimitive<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("MeshPrimitive");
            ds.field("lod0", &self.lod0());
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `Model`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_model_unchecked`.
    pub fn root_as_model(buf: &[u8]) -> Result<Model, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::root::<Model>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `Model` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_model_unchecked`.
    pub fn size_prefixed_root_as_model(
        buf: &[u8],
    ) -> Result<Model, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::size_prefixed_root::<Model>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `Model` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_model_unchecked`.
    pub fn root_as_model_with_opts<'b, 'o>(
        opts: &'o flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<Model<'b>, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::root_with_opts::<Model<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `Model` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_model_unchecked`.
    pub fn size_prefixed_root_as_model_with_opts<'b, 'o>(
        opts: &'o flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<Model<'b>, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::size_prefixed_root_with_opts::<Model<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a Model and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `Model`.
    pub unsafe fn root_as_model_unchecked(buf: &[u8]) -> Model {
        unsafe { flatbuffers::root_unchecked::<Model>(buf) }
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed Model and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `Model`.
    pub unsafe fn size_prefixed_root_as_model_unchecked(buf: &[u8]) -> Model {
        unsafe { flatbuffers::size_prefixed_root_unchecked::<Model>(buf) }
    }
    #[inline]
    pub fn finish_model_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
        fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        root: flatbuffers::WIPOffset<Model<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_model_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
        fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        root: flatbuffers::WIPOffset<Model<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod alpaca
