#version 460

#extension GL_EXT_samplerless_texture_functions : enable

#include "../common.glsl"
#include "../bindings.glsl"
#include "../projection.glsl"
#include "push_constants.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (coord.x >= int(push_constants.width) || coord.y >= int(push_constants.height)) {
        return;
    }

    Scene scene = SceneBuffer(push_constants.scene_buffer_device_address).data;

    float depth = texelFetch(graph_textures[push_constants.depth_descriptor_id], coord, 0).r;

    vec4 guide = vec4(0.0);
    if (depth > 0.0) {
        vec3 world_position = world_position_from_depth(
            scene.main_camera.inverse_jittered_view_projection,
            coord,
            ivec2(int(push_constants.width), int(push_constants.height)),
            depth
        );

        float linear_z = distance(world_position, scene.main_camera.position);
        vec3 normal = normalize(texelFetch(graph_textures[push_constants.normal_descriptor_id], coord, 0).xyz);

        guide = vec4(linear_z, normal);
    }

    imageStore(storage_images_rgba16f[push_constants.guide_storage_id], coord, guide);
}
